# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autobrew_mainpage_v1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AutoBrew(object):
    def setupUi(self, AutoBrew):
        AutoBrew.setObjectName("AutoBrew")
        AutoBrew.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(AutoBrew)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 800, 431))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Tabs.setFont(font)
        self.Tabs.setObjectName("Tabs")
        self.TestorProd = QtWidgets.QWidget()
        self.TestorProd.setObjectName("TestorProd")
        self.PageHeading = QtWidgets.QLabel(self.TestorProd)
        self.PageHeading.setGeometry(QtCore.QRect(10, 30, 771, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PageHeading.setFont(font)
        self.PageHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.PageHeading.setObjectName("PageHeading")
        self.TestPCButton = QtWidgets.QPushButton(self.TestorProd)
        self.TestPCButton.setGeometry(QtCore.QRect(430, 220, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TestPCButton.setFont(font)
        self.TestPCButton.setObjectName("TestPCButton")
        self.TestVerbiage = QtWidgets.QLabel(self.TestorProd)
        self.TestVerbiage.setGeometry(QtCore.QRect(270, 300, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TestVerbiage.setFont(font)
        self.TestVerbiage.setAlignment(QtCore.Qt.AlignCenter)
        self.TestVerbiage.setWordWrap(True)
        self.TestVerbiage.setObjectName("TestVerbiage")
        self.LivePiButton = QtWidgets.QPushButton(self.TestorProd)
        self.LivePiButton.setGeometry(QtCore.QRect(110, 120, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LivePiButton.setFont(font)
        self.LivePiButton.setObjectName("LivePiButton")
        self.TestPiButton = QtWidgets.QPushButton(self.TestorProd)
        self.TestPiButton.setGeometry(QtCore.QRect(110, 220, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TestPiButton.setFont(font)
        self.TestPiButton.setObjectName("TestPiButton")
        self.LivePCButton = QtWidgets.QPushButton(self.TestorProd)
        self.LivePCButton.setGeometry(QtCore.QRect(430, 120, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LivePCButton.setFont(font)
        self.LivePCButton.setObjectName("LivePCButton")
        self.Tabs.addTab(self.TestorProd, "")
        self.RecipeTab = QtWidgets.QWidget()
        self.RecipeTab.setObjectName("RecipeTab")
        self.Rest5Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest5Time.setGeometry(QtCore.QRect(460, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest5Time.setFont(font)
        self.Rest5Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest5Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest5Time.setSpecialValueText("")
        self.Rest5Time.setMaximum(120)
        self.Rest5Time.setProperty("value", 0)
        self.Rest5Time.setObjectName("Rest5Time")
        self.Rest6Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest6Temp.setGeometry(QtCore.QRect(290, 311, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest6Temp.setFont(font)
        self.Rest6Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest6Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest6Temp.setSpecialValueText("")
        self.Rest6Temp.setMaximum(200)
        self.Rest6Temp.setProperty("value", 0)
        self.Rest6Temp.setObjectName("Rest6Temp")
        self.label_9 = QtWidgets.QLabel(self.RecipeTab)
        self.label_9.setGeometry(QtCore.QRect(340, 20, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.ExitButtonRecipe = QtWidgets.QPushButton(self.RecipeTab)
        self.ExitButtonRecipe.setGeometry(QtCore.QRect(650, 280, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExitButtonRecipe.setFont(font)
        self.ExitButtonRecipe.setObjectName("ExitButtonRecipe")
        self.Rest2Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest2Temp.setGeometry(QtCore.QRect(290, 112, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest2Temp.setFont(font)
        self.Rest2Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest2Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest2Temp.setSpecialValueText("")
        self.Rest2Temp.setMaximum(200)
        self.Rest2Temp.setProperty("value", 0)
        self.Rest2Temp.setObjectName("Rest2Temp")
        self.Rest4Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest4Time.setGeometry(QtCore.QRect(460, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest4Time.setFont(font)
        self.Rest4Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest4Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest4Time.setSpecialValueText("")
        self.Rest4Time.setMaximum(120)
        self.Rest4Time.setProperty("value", 0)
        self.Rest4Time.setObjectName("Rest4Time")
        self.Rest4Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest4Temp.setGeometry(QtCore.QRect(290, 211, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest4Temp.setFont(font)
        self.Rest4Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest4Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest4Temp.setSpecialValueText("")
        self.Rest4Temp.setMaximum(200)
        self.Rest4Temp.setProperty("value", 0)
        self.Rest4Temp.setObjectName("Rest4Temp")
        self.Rest6Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest6Time.setGeometry(QtCore.QRect(460, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest6Time.setFont(font)
        self.Rest6Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest6Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest6Time.setSpecialValueText("")
        self.Rest6Time.setMaximum(120)
        self.Rest6Time.setProperty("value", 0)
        self.Rest6Time.setObjectName("Rest6Time")
        self.label_10 = QtWidgets.QLabel(self.RecipeTab)
        self.label_10.setGeometry(QtCore.QRect(510, 20, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.Rest2Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest2Time.setGeometry(QtCore.QRect(460, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest2Time.setFont(font)
        self.Rest2Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest2Time.setSpecialValueText("")
        self.Rest2Time.setMaximum(120)
        self.Rest2Time.setProperty("value", 0)
        self.Rest2Time.setObjectName("Rest2Time")
        self.Rest1Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest1Temp.setGeometry(QtCore.QRect(290, 61, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest1Temp.setFont(font)
        self.Rest1Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest1Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest1Temp.setSpecialValueText("")
        self.Rest1Temp.setMaximum(200)
        self.Rest1Temp.setProperty("value", 0)
        self.Rest1Temp.setObjectName("Rest1Temp")
        self.BrewButton = QtWidgets.QPushButton(self.RecipeTab)
        self.BrewButton.setGeometry(QtCore.QRect(650, 170, 93, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BrewButton.setFont(font)
        self.BrewButton.setObjectName("BrewButton")
        self.Rest3Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest3Temp.setGeometry(QtCore.QRect(290, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest3Temp.setFont(font)
        self.Rest3Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest3Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest3Temp.setSpecialValueText("")
        self.Rest3Temp.setMaximum(200)
        self.Rest3Temp.setProperty("value", 0)
        self.Rest3Temp.setObjectName("Rest3Temp")
        self.Rest3Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest3Time.setGeometry(QtCore.QRect(460, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest3Time.setFont(font)
        self.Rest3Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest3Time.setSpecialValueText("")
        self.Rest3Time.setMaximum(120)
        self.Rest3Time.setProperty("value", 0)
        self.Rest3Time.setObjectName("Rest3Time")
        self.Rest5Temp = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest5Temp.setGeometry(QtCore.QRect(290, 261, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest5Temp.setFont(font)
        self.Rest5Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest5Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest5Temp.setSpecialValueText("")
        self.Rest5Temp.setMaximum(200)
        self.Rest5Temp.setProperty("value", 0)
        self.Rest5Temp.setObjectName("Rest5Temp")
        self.Rest1Time = QtWidgets.QSpinBox(self.RecipeTab)
        self.Rest1Time.setGeometry(QtCore.QRect(460, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rest1Time.setFont(font)
        self.Rest1Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.Rest1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Rest1Time.setSpecialValueText("")
        self.Rest1Time.setMaximum(999)
        self.Rest1Time.setProperty("value", 0)
        self.Rest1Time.setObjectName("Rest1Time")
        self.Rest1Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest1Button.setGeometry(QtCore.QRect(10, 30, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest1Button.setFont(font)
        self.Rest1Button.setText("")
        self.Rest1Button.setCheckable(True)
        self.Rest1Button.setChecked(False)
        self.Rest1Button.setObjectName("Rest1Button")
        self.Rest2Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest2Button.setGeometry(QtCore.QRect(10, 120, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest2Button.setFont(font)
        self.Rest2Button.setText("")
        self.Rest2Button.setCheckable(True)
        self.Rest2Button.setObjectName("Rest2Button")
        self.Rest3Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest3Button.setGeometry(QtCore.QRect(10, 210, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest3Button.setFont(font)
        self.Rest3Button.setText("")
        self.Rest3Button.setCheckable(True)
        self.Rest3Button.setObjectName("Rest3Button")
        self.Rest4Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest4Button.setGeometry(QtCore.QRect(10, 300, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest4Button.setFont(font)
        self.Rest4Button.setText("")
        self.Rest4Button.setCheckable(True)
        self.Rest4Button.setObjectName("Rest4Button")
        self.Rest5Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest5Button.setGeometry(QtCore.QRect(140, 30, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest5Button.setFont(font)
        self.Rest5Button.setText("")
        self.Rest5Button.setCheckable(True)
        self.Rest5Button.setChecked(False)
        self.Rest5Button.setObjectName("Rest5Button")
        self.Rest6Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest6Button.setGeometry(QtCore.QRect(140, 120, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest6Button.setFont(font)
        self.Rest6Button.setText("")
        self.Rest6Button.setCheckable(True)
        self.Rest6Button.setChecked(False)
        self.Rest6Button.setObjectName("Rest6Button")
        self.Rest7Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest7Button.setGeometry(QtCore.QRect(140, 210, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest7Button.setFont(font)
        self.Rest7Button.setText("")
        self.Rest7Button.setCheckable(True)
        self.Rest7Button.setChecked(False)
        self.Rest7Button.setObjectName("Rest7Button")
        self.Rest8Button = QtWidgets.QPushButton(self.RecipeTab)
        self.Rest8Button.setGeometry(QtCore.QRect(140, 300, 111, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Rest8Button.setFont(font)
        self.Rest8Button.setText("")
        self.Rest8Button.setCheckable(True)
        self.Rest8Button.setChecked(False)
        self.Rest8Button.setObjectName("Rest8Button")
        self.Tabs.addTab(self.RecipeTab, "")
        self.ScheduleTab = QtWidgets.QWidget()
        self.ScheduleTab.setObjectName("ScheduleTab")
        self.ScheduleBox = QtWidgets.QTextEdit(self.ScheduleTab)
        self.ScheduleBox.setGeometry(QtCore.QRect(10, 90, 731, 291))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setKerning(False)
        self.ScheduleBox.setFont(font)
        self.ScheduleBox.setObjectName("ScheduleBox")
        self.label_34 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_34.setGeometry(QtCore.QRect(20, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_35.setGeometry(QtCore.QRect(310, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_36.setGeometry(QtCore.QRect(600, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_37.setGeometry(QtCore.QRect(670, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_39.setGeometry(QtCore.QRect(270, 20, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_40.setGeometry(QtCore.QRect(440, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_38 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_38.setGeometry(QtCore.QRect(600, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_41 = QtWidgets.QLabel(self.ScheduleTab)
        self.label_41.setGeometry(QtCore.QRect(680, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.Tabs.addTab(self.ScheduleTab, "")
        self.AutoBrewTab = QtWidgets.QWidget()
        self.AutoBrewTab.setObjectName("AutoBrewTab")
        self.TimeOfDay = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.TimeOfDay.setGeometry(QtCore.QRect(630, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.TimeOfDay.setFont(font)
        self.TimeOfDay.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeOfDay.setObjectName("TimeOfDay")
        self.label_15 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_15.setGeometry(QtCore.QRect(220, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.TotalElapsedTime = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.TotalElapsedTime.setGeometry(QtCore.QRect(370, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.TotalElapsedTime.setFont(font)
        self.TotalElapsedTime.setInputMask("")
        self.TotalElapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalElapsedTime.setObjectName("TotalElapsedTime")
        self.label_16 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_16.setGeometry(QtCore.QRect(490, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_17.setGeometry(QtCore.QRect(20, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_18.setGeometry(QtCore.QRect(40, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_19.setGeometry(QtCore.QRect(280, 80, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_20.setGeometry(QtCore.QRect(400, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_21.setGeometry(QtCore.QRect(500, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_22.setGeometry(QtCore.QRect(500, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.CurrentRecipeStepName = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentRecipeStepName.setGeometry(QtCore.QRect(12, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentRecipeStepName.setFont(font)
        self.CurrentRecipeStepName.setInputMask("")
        self.CurrentRecipeStepName.setFrame(True)
        self.CurrentRecipeStepName.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentRecipeStepName.setReadOnly(False)
        self.CurrentRecipeStepName.setObjectName("CurrentRecipeStepName")
        self.CurrentRecipeStepElapsed = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentRecipeStepElapsed.setGeometry(QtCore.QRect(390, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentRecipeStepElapsed.setFont(font)
        self.CurrentRecipeStepElapsed.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentRecipeStepElapsed.setObjectName("CurrentRecipeStepElapsed")
        self.CurrentRecipeStepTimeToNext = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentRecipeStepTimeToNext.setGeometry(QtCore.QRect(490, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentRecipeStepTimeToNext.setFont(font)
        self.CurrentRecipeStepTimeToNext.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentRecipeStepTimeToNext.setObjectName("CurrentRecipeStepTimeToNext")
        self.CurrentRecipeStepBegan = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentRecipeStepBegan.setGeometry(QtCore.QRect(230, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentRecipeStepBegan.setFont(font)
        self.CurrentRecipeStepBegan.setText("")
        self.CurrentRecipeStepBegan.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentRecipeStepBegan.setObjectName("CurrentRecipeStepBegan")
        self.CurrentTempStepHLTElapsed = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentTempStepHLTElapsed.setGeometry(QtCore.QRect(390, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentTempStepHLTElapsed.setFont(font)
        self.CurrentTempStepHLTElapsed.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTempStepHLTElapsed.setObjectName("CurrentTempStepHLTElapsed")
        self.CurrentTempStepHLTTimeToNext = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentTempStepHLTTimeToNext.setGeometry(QtCore.QRect(490, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentTempStepHLTTimeToNext.setFont(font)
        self.CurrentTempStepHLTTimeToNext.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTempStepHLTTimeToNext.setObjectName("CurrentTempStepHLTTimeToNext")
        self.CurrentTempStepHLTBegan = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentTempStepHLTBegan.setGeometry(QtCore.QRect(230, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentTempStepHLTBegan.setFont(font)
        self.CurrentTempStepHLTBegan.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTempStepHLTBegan.setObjectName("CurrentTempStepHLTBegan")
        self.label_25 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_25.setGeometry(QtCore.QRect(110, 160, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_26.setGeometry(QtCore.QRect(20, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_27.setGeometry(QtCore.QRect(250, 330, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_28.setGeometry(QtCore.QRect(170, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_30 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_30.setGeometry(QtCore.QRect(380, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.UpcomingRecipeStepBegins = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.UpcomingRecipeStepBegins.setGeometry(QtCore.QRect(370, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.UpcomingRecipeStepBegins.setFont(font)
        self.UpcomingRecipeStepBegins.setAlignment(QtCore.Qt.AlignCenter)
        self.UpcomingRecipeStepBegins.setObjectName("UpcomingRecipeStepBegins")
        self.UpcomingRecipeStepName = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.UpcomingRecipeStepName.setGeometry(QtCore.QRect(120, 290, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.UpcomingRecipeStepName.setFont(font)
        self.UpcomingRecipeStepName.setInputMask("")
        self.UpcomingRecipeStepName.setAlignment(QtCore.Qt.AlignCenter)
        self.UpcomingRecipeStepName.setObjectName("UpcomingRecipeStepName")
        self.UpcomingHLTBegins = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.UpcomingHLTBegins.setGeometry(QtCore.QRect(370, 330, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.UpcomingHLTBegins.setFont(font)
        self.UpcomingHLTBegins.setAlignment(QtCore.Qt.AlignCenter)
        self.UpcomingHLTBegins.setObjectName("UpcomingHLTBegins")
        self.CurrentTempStepMashSet = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentTempStepMashSet.setGeometry(QtCore.QRect(180, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentTempStepMashSet.setFont(font)
        self.CurrentTempStepMashSet.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTempStepMashSet.setObjectName("CurrentTempStepMashSet")
        self.CurrentTempStepHLTSet = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.CurrentTempStepHLTSet.setGeometry(QtCore.QRect(180, 160, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.CurrentTempStepHLTSet.setFont(font)
        self.CurrentTempStepHLTSet.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentTempStepHLTSet.setObjectName("CurrentTempStepHLTSet")
        self.UpcomingMashTempSet = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.UpcomingMashTempSet.setGeometry(QtCore.QRect(320, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.UpcomingMashTempSet.setFont(font)
        self.UpcomingMashTempSet.setAlignment(QtCore.Qt.AlignCenter)
        self.UpcomingMashTempSet.setObjectName("UpcomingMashTempSet")
        self.UpcomingHLTTempSet = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.UpcomingHLTTempSet.setGeometry(QtCore.QRect(320, 330, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.UpcomingHLTTempSet.setFont(font)
        self.UpcomingHLTTempSet.setAlignment(QtCore.Qt.AlignCenter)
        self.UpcomingHLTTempSet.setObjectName("UpcomingHLTTempSet")
        self.StartButton = QtWidgets.QPushButton(self.AutoBrewTab)
        self.StartButton.setGeometry(QtCore.QRect(540, 300, 93, 61))
        self.StartButton.setObjectName("StartButton")
        self.ExitButtonAutoBrew = QtWidgets.QPushButton(self.AutoBrewTab)
        self.ExitButtonAutoBrew.setGeometry(QtCore.QRect(650, 300, 93, 61))
        self.ExitButtonAutoBrew.setObjectName("ExitButtonAutoBrew")
        self.CurrentMashTempLabel_2 = QtWidgets.QLabel(self.AutoBrewTab)
        self.CurrentMashTempLabel_2.setGeometry(QtCore.QRect(630, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CurrentMashTempLabel_2.setFont(font)
        self.CurrentMashTempLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentMashTempLabel_2.setObjectName("CurrentMashTempLabel_2")
        self.AutobrewCurrentMashTempDisplay = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.AutobrewCurrentMashTempDisplay.setGeometry(QtCore.QRect(630, 120, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AutobrewCurrentMashTempDisplay.setFont(font)
        self.AutobrewCurrentMashTempDisplay.setStyleSheet("border: 1px groove gray\n"
"")
        self.AutobrewCurrentMashTempDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.AutobrewCurrentMashTempDisplay.setObjectName("AutobrewCurrentMashTempDisplay")
        self.CurrentMashTempLabel_3 = QtWidgets.QLabel(self.AutoBrewTab)
        self.CurrentMashTempLabel_3.setGeometry(QtCore.QRect(620, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentMashTempLabel_3.setFont(font)
        self.CurrentMashTempLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentMashTempLabel_3.setObjectName("CurrentMashTempLabel_3")
        self.AutobrewCurrentHLTTempDisplay = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.AutobrewCurrentHLTTempDisplay.setGeometry(QtCore.QRect(700, 120, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AutobrewCurrentHLTTempDisplay.setFont(font)
        self.AutobrewCurrentHLTTempDisplay.setStyleSheet("border: 1px groove gray\n"
"")
        self.AutobrewCurrentHLTTempDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.AutobrewCurrentHLTTempDisplay.setObjectName("AutobrewCurrentHLTTempDisplay")
        self.label_32 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_32.setGeometry(QtCore.QRect(640, 210, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.AutobrewPumpStatus = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.AutobrewPumpStatus.setGeometry(QtCore.QRect(630, 240, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AutobrewPumpStatus.setFont(font)
        self.AutobrewPumpStatus.setStyleSheet("border: 1px groove gray\n"
"")
        self.AutobrewPumpStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.AutobrewPumpStatus.setObjectName("AutobrewPumpStatus")
        self.AutobrewHLTStatus = QtWidgets.QLineEdit(self.AutoBrewTab)
        self.AutobrewHLTStatus.setGeometry(QtCore.QRect(700, 240, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AutobrewHLTStatus.setFont(font)
        self.AutobrewHLTStatus.setStyleSheet("border: 1px groove gray\n"
"")
        self.AutobrewHLTStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.AutobrewHLTStatus.setObjectName("AutobrewHLTStatus")
        self.label_23 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_23.setGeometry(QtCore.QRect(170, 80, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_24.setGeometry(QtCore.QRect(310, 250, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.CurrentMashTempLabel_4 = QtWidgets.QLabel(self.AutoBrewTab)
        self.CurrentMashTempLabel_4.setGeometry(QtCore.QRect(700, 90, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CurrentMashTempLabel_4.setFont(font)
        self.CurrentMashTempLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentMashTempLabel_4.setObjectName("CurrentMashTempLabel_4")
        self.label_33 = QtWidgets.QLabel(self.AutoBrewTab)
        self.label_33.setGeometry(QtCore.QRect(700, 210, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.CurrentMashTempLabel_5 = QtWidgets.QLabel(self.AutoBrewTab)
        self.CurrentMashTempLabel_5.setGeometry(QtCore.QRect(620, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentMashTempLabel_5.setFont(font)
        self.CurrentMashTempLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentMashTempLabel_5.setObjectName("CurrentMashTempLabel_5")
        self.Tabs.addTab(self.AutoBrewTab, "")
        self.ManualControlTab = QtWidgets.QWidget()
        self.ManualControlTab.setObjectName("ManualControlTab")
        self.PumpRunningLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.PumpRunningLabel.setGeometry(QtCore.QRect(458, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PumpRunningLabel.setFont(font)
        self.PumpRunningLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PumpRunningLabel.setObjectName("PumpRunningLabel")
        self.CurrentMashTempLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.CurrentMashTempLabel.setGeometry(QtCore.QRect(360, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CurrentMashTempLabel.setFont(font)
        self.CurrentMashTempLabel.setObjectName("CurrentMashTempLabel")
        self.RespectMashFloatSwitchPump = QtWidgets.QCheckBox(self.ManualControlTab)
        self.RespectMashFloatSwitchPump.setGeometry(QtCore.QRect(470, 130, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.RespectMashFloatSwitchPump.setFont(font)
        self.RespectMashFloatSwitchPump.setChecked(True)
        self.RespectMashFloatSwitchPump.setObjectName("RespectMashFloatSwitchPump")
        self.CurrentHLTTempLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.CurrentHLTTempLabel.setGeometry(QtCore.QRect(360, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CurrentHLTTempLabel.setFont(font)
        self.CurrentHLTTempLabel.setObjectName("CurrentHLTTempLabel")
        self.PumpOn = QtWidgets.QPushButton(self.ManualControlTab)
        self.PumpOn.setGeometry(QtCore.QRect(120, 100, 93, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PumpOn.setFont(font)
        self.PumpOn.setStyleSheet("border: 1px groove gray\n"
"")
        self.PumpOn.setObjectName("PumpOn")
        self.RespectHLTTempSet = QtWidgets.QCheckBox(self.ManualControlTab)
        self.RespectHLTTempSet.setGeometry(QtCore.QRect(470, 260, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.RespectHLTTempSet.setFont(font)
        self.RespectHLTTempSet.setChecked(True)
        self.RespectHLTTempSet.setObjectName("RespectHLTTempSet")
        self.HLTOn = QtWidgets.QPushButton(self.ManualControlTab)
        self.HLTOn.setGeometry(QtCore.QRect(120, 260, 93, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HLTOn.setFont(font)
        self.HLTOn.setStyleSheet("border: 1px groove gray\n"
"")
        self.HLTOn.setObjectName("HLTOn")
        self.MashFloatText = QtWidgets.QLineEdit(self.ManualControlTab)
        self.MashFloatText.setGeometry(QtCore.QRect(690, 30, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.MashFloatText.setFont(font)
        self.MashFloatText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.MashFloatText.setObjectName("MashFloatText")
        self.RespectHLTFloatSwitchHLT = QtWidgets.QCheckBox(self.ManualControlTab)
        self.RespectHLTFloatSwitchHLT.setGeometry(QtCore.QRect(470, 290, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.RespectHLTFloatSwitchHLT.setFont(font)
        self.RespectHLTFloatSwitchHLT.setChecked(True)
        self.RespectHLTFloatSwitchHLT.setObjectName("RespectHLTFloatSwitchHLT")
        self.MashFloatLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.MashFloatLabel.setGeometry(QtCore.QRect(598, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.MashFloatLabel.setFont(font)
        self.MashFloatLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MashFloatLabel.setObjectName("MashFloatLabel")
        self.HLTRunningLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.HLTRunningLabel.setGeometry(QtCore.QRect(470, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HLTRunningLabel.setFont(font)
        self.HLTRunningLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HLTRunningLabel.setObjectName("HLTRunningLabel")
        self.MashTempSetLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.MashTempSetLabel.setGeometry(QtCore.QRect(260, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MashTempSetLabel.setFont(font)
        self.MashTempSetLabel.setObjectName("MashTempSetLabel")
        self.HLTTempSetLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.HLTTempSetLabel.setGeometry(QtCore.QRect(260, 220, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HLTTempSetLabel.setFont(font)
        self.HLTTempSetLabel.setObjectName("HLTTempSetLabel")
        self.PumpLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.PumpLabel.setGeometry(QtCore.QRect(10, 50, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PumpLabel.setFont(font)
        self.PumpLabel.setObjectName("PumpLabel")
        self.RespectHLTFloatSwitchPump = QtWidgets.QCheckBox(self.ManualControlTab)
        self.RespectHLTFloatSwitchPump.setGeometry(QtCore.QRect(470, 170, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.RespectHLTFloatSwitchPump.setFont(font)
        self.RespectHLTFloatSwitchPump.setChecked(True)
        self.RespectHLTFloatSwitchPump.setObjectName("RespectHLTFloatSwitchPump")
        self.CurrentMashTempDisplay = QtWidgets.QLineEdit(self.ManualControlTab)
        self.CurrentMashTempDisplay.setGeometry(QtCore.QRect(380, 100, 71, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentMashTempDisplay.setFont(font)
        self.CurrentMashTempDisplay.setStyleSheet("border: 1px groove gray\n"
"")
        self.CurrentMashTempDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentMashTempDisplay.setObjectName("CurrentMashTempDisplay")
        self.MashTempSet = QtWidgets.QSpinBox(self.ManualControlTab)
        self.MashTempSet.setGeometry(QtCore.QRect(240, 100, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MashTempSet.setFont(font)
        self.MashTempSet.setStyleSheet("QSpinBox { border: 1px groove gray} \n"
"QSpinBox::up-button { subcontrol-position: top right; width: 40px; height: 40px;}\n"
"QSpinBox::down-button { subcontrol-position: bottom right; width: 40px; height: 40px;}")
        self.MashTempSet.setAlignment(QtCore.Qt.AlignCenter)
        self.MashTempSet.setMaximum(200)
        self.MashTempSet.setProperty("value", 100)
        self.MashTempSet.setObjectName("MashTempSet")
        self.RespectMashTempSet = QtWidgets.QCheckBox(self.ManualControlTab)
        self.RespectMashTempSet.setGeometry(QtCore.QRect(470, 80, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.RespectMashTempSet.setFont(font)
        self.RespectMashTempSet.setChecked(True)
        self.RespectMashTempSet.setObjectName("RespectMashTempSet")
        self.HLTRunningText = QtWidgets.QLineEdit(self.ManualControlTab)
        self.HLTRunningText.setGeometry(QtCore.QRect(520, 60, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.HLTRunningText.setFont(font)
        self.HLTRunningText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.HLTRunningText.setObjectName("HLTRunningText")
        self.Go = QtWidgets.QPushButton(self.ManualControlTab)
        self.Go.setEnabled(False)
        self.Go.setGeometry(QtCore.QRect(470, 330, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Go.setFont(font)
        self.Go.setObjectName("Go")
        self.HLTTempSet = QtWidgets.QSpinBox(self.ManualControlTab)
        self.HLTTempSet.setGeometry(QtCore.QRect(240, 260, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HLTTempSet.setFont(font)
        self.HLTTempSet.setStyleSheet("QSpinBox { border: 1px groove gray} \n"
"QSpinBox::up-button { subcontrol-position: top right; width: 40px; height: 40px;}\n"
"QSpinBox::down-button { subcontrol-position: bottom right; width: 40px; height: 40px;}")
        self.HLTTempSet.setAlignment(QtCore.Qt.AlignCenter)
        self.HLTTempSet.setMaximum(200)
        self.HLTTempSet.setProperty("value", 110)
        self.HLTTempSet.setObjectName("HLTTempSet")
        self.HLTFloatLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.HLTFloatLabel.setGeometry(QtCore.QRect(600, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HLTFloatLabel.setFont(font)
        self.HLTFloatLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HLTFloatLabel.setObjectName("HLTFloatLabel")
        self.PumpRunningText = QtWidgets.QLineEdit(self.ManualControlTab)
        self.PumpRunningText.setGeometry(QtCore.QRect(518, 30, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.PumpRunningText.setFont(font)
        self.PumpRunningText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.PumpRunningText.setObjectName("PumpRunningText")
        self.HLTLabel = QtWidgets.QLabel(self.ManualControlTab)
        self.HLTLabel.setGeometry(QtCore.QRect(10, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HLTLabel.setFont(font)
        self.HLTLabel.setObjectName("HLTLabel")
        self.HLTOff = QtWidgets.QPushButton(self.ManualControlTab)
        self.HLTOff.setGeometry(QtCore.QRect(10, 260, 93, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HLTOff.setFont(font)
        self.HLTOff.setStyleSheet("border: 1px groove gray\n"
"")
        self.HLTOff.setObjectName("HLTOff")
        self.PumpOff = QtWidgets.QPushButton(self.ManualControlTab)
        self.PumpOff.setGeometry(QtCore.QRect(10, 100, 93, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PumpOff.setFont(font)
        self.PumpOff.setStyleSheet("border: 1px groove gray\n"
"")
        self.PumpOff.setObjectName("PumpOff")
        self.CurrentHLTTempDisplay = QtWidgets.QLineEdit(self.ManualControlTab)
        self.CurrentHLTTempDisplay.setGeometry(QtCore.QRect(380, 260, 71, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentHLTTempDisplay.setFont(font)
        self.CurrentHLTTempDisplay.setStyleSheet("border: 1px groove gray\n"
"")
        self.CurrentHLTTempDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentHLTTempDisplay.setObjectName("CurrentHLTTempDisplay")
        self.HLTFloatText = QtWidgets.QLineEdit(self.ManualControlTab)
        self.HLTFloatText.setGeometry(QtCore.QRect(690, 60, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.HLTFloatText.setFont(font)
        self.HLTFloatText.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.HLTFloatText.setObjectName("HLTFloatText")
        self.ReturntoSessionButton = QtWidgets.QPushButton(self.ManualControlTab)
        self.ReturntoSessionButton.setGeometry(QtCore.QRect(640, 330, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ReturntoSessionButton.setFont(font)
        self.ReturntoSessionButton.setObjectName("ReturntoSessionButton")
        self.Tabs.addTab(self.ManualControlTab, "")
        self.Log_Tab = QtWidgets.QWidget()
        self.Log_Tab.setObjectName("Log_Tab")
        self.LogBox = QtWidgets.QTextEdit(self.Log_Tab)
        self.LogBox.setGeometry(QtCore.QRect(20, 10, 761, 311))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LogBox.setFont(font)
        self.LogBox.setObjectName("LogBox")
        self.ExportLogButton = QtWidgets.QPushButton(self.Log_Tab)
        self.ExportLogButton.setGeometry(QtCore.QRect(610, 330, 171, 51))
        self.ExportLogButton.setObjectName("ExportLogButton")
        self.Tabs.addTab(self.Log_Tab, "")
        self.ChartTab = QtWidgets.QWidget()
        self.ChartTab.setObjectName("ChartTab")
        self.ExportChartButton = QtWidgets.QPushButton(self.ChartTab)
        self.ExportChartButton.setGeometry(QtCore.QRect(610, 330, 171, 51))
        self.ExportChartButton.setObjectName("ExportChartButton")
        self.ChartBox = QtWidgets.QTextEdit(self.ChartTab)
        self.ChartBox.setGeometry(QtCore.QRect(10, 0, 771, 321))
        self.ChartBox.setObjectName("ChartBox")
        self.Tabs.addTab(self.ChartTab, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.label_11 = QtWidgets.QLabel(self.SettingsTab)
        self.label_11.setGeometry(QtCore.QRect(90, 40, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.SettingsTab)
        self.label_12.setGeometry(QtCore.QRect(130, 160, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.SettingsTab)
        self.label_13.setGeometry(QtCore.QRect(90, 100, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.MTHLTDifferential = QtWidgets.QDoubleSpinBox(self.SettingsTab)
        self.MTHLTDifferential.setGeometry(QtCore.QRect(590, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MTHLTDifferential.setFont(font)
        self.MTHLTDifferential.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.MTHLTDifferential.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MTHLTDifferential.setDecimals(1)
        self.MTHLTDifferential.setSingleStep(0.1)
        self.MTHLTDifferential.setProperty("value", 12.0)
        self.MTHLTDifferential.setObjectName("MTHLTDifferential")
        self.label_42 = QtWidgets.QLabel(self.SettingsTab)
        self.label_42.setGeometry(QtCore.QRect(130, 220, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.HLTRaiseTime = QtWidgets.QDoubleSpinBox(self.SettingsTab)
        self.HLTRaiseTime.setGeometry(QtCore.QRect(590, 100, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HLTRaiseTime.setFont(font)
        self.HLTRaiseTime.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.HLTRaiseTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HLTRaiseTime.setDecimals(1)
        self.HLTRaiseTime.setSingleStep(0.1)
        self.HLTRaiseTime.setProperty("value", 1.7)
        self.HLTRaiseTime.setObjectName("HLTRaiseTime")
        self.MTTempDrop = QtWidgets.QDoubleSpinBox(self.SettingsTab)
        self.MTTempDrop.setGeometry(QtCore.QRect(590, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MTTempDrop.setFont(font)
        self.MTTempDrop.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.MTTempDrop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MTTempDrop.setDecimals(1)
        self.MTTempDrop.setSingleStep(0.1)
        self.MTTempDrop.setProperty("value", 7.0)
        self.MTTempDrop.setObjectName("MTTempDrop")
        self.MTRaiseTime = QtWidgets.QDoubleSpinBox(self.SettingsTab)
        self.MTRaiseTime.setGeometry(QtCore.QRect(590, 220, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MTRaiseTime.setFont(font)
        self.MTRaiseTime.setStyleSheet("QDoubleSpinBox { border: 1px inset grey; } \n"
"QDoubleSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QDoubleSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.MTRaiseTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MTRaiseTime.setDecimals(1)
        self.MTRaiseTime.setSingleStep(0.1)
        self.MTRaiseTime.setProperty("value", 0.7)
        self.MTRaiseTime.setObjectName("MTRaiseTime")
        self.TwilioLabel1 = QtWidgets.QLabel(self.SettingsTab)
        self.TwilioLabel1.setGeometry(QtCore.QRect(70, 270, 201, 21))
        self.TwilioLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TwilioLabel1.setObjectName("TwilioLabel1")
        self.TwilioLabel2 = QtWidgets.QLabel(self.SettingsTab)
        self.TwilioLabel2.setGeometry(QtCore.QRect(130, 300, 141, 20))
        self.TwilioLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TwilioLabel2.setObjectName("TwilioLabel2")
        self.TwilioLabel3 = QtWidgets.QLabel(self.SettingsTab)
        self.TwilioLabel3.setGeometry(QtCore.QRect(130, 330, 141, 16))
        self.TwilioLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TwilioLabel3.setObjectName("TwilioLabel3")
        self.TwilioLabel4 = QtWidgets.QLabel(self.SettingsTab)
        self.TwilioLabel4.setGeometry(QtCore.QRect(130, 360, 141, 16))
        self.TwilioLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TwilioLabel4.setObjectName("TwilioLabel4")
        self.TwilioSID = QtWidgets.QLineEdit(self.SettingsTab)
        self.TwilioSID.setGeometry(QtCore.QRect(280, 270, 381, 22))
        self.TwilioSID.setPlaceholderText("")
        self.TwilioSID.setObjectName("TwilioSID")
        self.TwilioAuthToken = QtWidgets.QLineEdit(self.SettingsTab)
        self.TwilioAuthToken.setGeometry(QtCore.QRect(280, 300, 351, 22))
        self.TwilioAuthToken.setPlaceholderText("")
        self.TwilioAuthToken.setObjectName("TwilioAuthToken")
        self.TwilioPhone = QtWidgets.QLineEdit(self.SettingsTab)
        self.TwilioPhone.setGeometry(QtCore.QRect(280, 330, 161, 22))
        self.TwilioPhone.setPlaceholderText("")
        self.TwilioPhone.setObjectName("TwilioPhone")
        self.TwilioSendTo = QtWidgets.QLineEdit(self.SettingsTab)
        self.TwilioSendTo.setGeometry(QtCore.QRect(280, 360, 161, 22))
        self.TwilioSendTo.setPlaceholderText("")
        self.TwilioSendTo.setObjectName("TwilioSendTo")
        self.Tabs.addTab(self.SettingsTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.DRest3Time = QtWidgets.QSpinBox(self.tab)
        self.DRest3Time.setGeometry(QtCore.QRect(500, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest3Time.setFont(font)
        self.DRest3Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest3Time.setSpecialValueText("")
        self.DRest3Time.setMaximum(120)
        self.DRest3Time.setProperty("value", 20)
        self.DRest3Time.setObjectName("DRest3Time")
        self.DRest2Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest2Temp.setGeometry(QtCore.QRect(330, 122, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest2Temp.setFont(font)
        self.DRest2Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest2Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest2Temp.setSpecialValueText("")
        self.DRest2Temp.setMaximum(200)
        self.DRest2Temp.setProperty("value", 122)
        self.DRest2Temp.setObjectName("DRest2Temp")
        self.DRest3Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest3Temp.setGeometry(QtCore.QRect(330, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest3Temp.setFont(font)
        self.DRest3Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest3Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest3Temp.setSpecialValueText("")
        self.DRest3Temp.setMaximum(200)
        self.DRest3Temp.setProperty("value", 133)
        self.DRest3Temp.setObjectName("DRest3Temp")
        self.DRest6Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest6Temp.setGeometry(QtCore.QRect(330, 280, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest6Temp.setFont(font)
        self.DRest6Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest6Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest6Temp.setSpecialValueText("")
        self.DRest6Temp.setMaximum(200)
        self.DRest6Temp.setProperty("value", 154)
        self.DRest6Temp.setObjectName("DRest6Temp")
        self.DRest5Time = QtWidgets.QSpinBox(self.tab)
        self.DRest5Time.setGeometry(QtCore.QRect(500, 240, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest5Time.setFont(font)
        self.DRest5Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest5Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest5Time.setSpecialValueText("")
        self.DRest5Time.setMaximum(120)
        self.DRest5Time.setProperty("value", 60)
        self.DRest5Time.setObjectName("DRest5Time")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(550, 40, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.DRest6Time = QtWidgets.QSpinBox(self.tab)
        self.DRest6Time.setGeometry(QtCore.QRect(500, 279, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest6Time.setFont(font)
        self.DRest6Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest6Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest6Time.setSpecialValueText("")
        self.DRest6Time.setMaximum(120)
        self.DRest6Time.setProperty("value", 60)
        self.DRest6Time.setObjectName("DRest6Time")
        self.DRest4Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest4Temp.setGeometry(QtCore.QRect(330, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest4Temp.setFont(font)
        self.DRest4Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest4Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest4Temp.setSpecialValueText("")
        self.DRest4Temp.setMaximum(200)
        self.DRest4Temp.setProperty("value", 140)
        self.DRest4Temp.setObjectName("DRest4Temp")
        self.DRest5Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest5Temp.setGeometry(QtCore.QRect(330, 241, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest5Temp.setFont(font)
        self.DRest5Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest5Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest5Temp.setSpecialValueText("")
        self.DRest5Temp.setMaximum(200)
        self.DRest5Temp.setProperty("value", 150)
        self.DRest5Temp.setObjectName("DRest5Temp")
        self.DRest1Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest1Temp.setGeometry(QtCore.QRect(330, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest1Temp.setFont(font)
        self.DRest1Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest1Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest1Temp.setSpecialValueText("")
        self.DRest1Temp.setMaximum(200)
        self.DRest1Temp.setProperty("value", 104)
        self.DRest1Temp.setObjectName("DRest1Temp")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(380, 40, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.DRest2Time = QtWidgets.QSpinBox(self.tab)
        self.DRest2Time.setGeometry(QtCore.QRect(500, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest2Time.setFont(font)
        self.DRest2Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest2Time.setSpecialValueText("")
        self.DRest2Time.setMaximum(120)
        self.DRest2Time.setProperty("value", 10)
        self.DRest2Time.setObjectName("DRest2Time")
        self.DRest4Time = QtWidgets.QSpinBox(self.tab)
        self.DRest4Time.setGeometry(QtCore.QRect(500, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest4Time.setFont(font)
        self.DRest4Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest4Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest4Time.setSpecialValueText("")
        self.DRest4Time.setMaximum(120)
        self.DRest4Time.setProperty("value", 60)
        self.DRest4Time.setObjectName("DRest4Time")
        self.DRest1Time = QtWidgets.QSpinBox(self.tab)
        self.DRest1Time.setGeometry(QtCore.QRect(500, 79, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest1Time.setFont(font)
        self.DRest1Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest1Time.setSpecialValueText("")
        self.DRest1Time.setMaximum(120)
        self.DRest1Time.setProperty("value", 15)
        self.DRest1Time.setObjectName("DRest1Time")
        self.DRest7Time = QtWidgets.QSpinBox(self.tab)
        self.DRest7Time.setGeometry(QtCore.QRect(500, 320, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest7Time.setFont(font)
        self.DRest7Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest7Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest7Time.setSpecialValueText("")
        self.DRest7Time.setMaximum(120)
        self.DRest7Time.setProperty("value", 30)
        self.DRest7Time.setObjectName("DRest7Time")
        self.DRest7Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest7Temp.setGeometry(QtCore.QRect(330, 320, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest7Temp.setFont(font)
        self.DRest7Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest7Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest7Temp.setSpecialValueText("")
        self.DRest7Temp.setMaximum(200)
        self.DRest7Temp.setProperty("value", 158)
        self.DRest7Temp.setObjectName("DRest7Temp")
        self.DRest8Time = QtWidgets.QSpinBox(self.tab)
        self.DRest8Time.setGeometry(QtCore.QRect(500, 360, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest8Time.setFont(font)
        self.DRest8Time.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest8Time.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest8Time.setSpecialValueText("")
        self.DRest8Time.setMaximum(120)
        self.DRest8Time.setProperty("value", 10)
        self.DRest8Time.setObjectName("DRest8Time")
        self.DRest8Temp = QtWidgets.QSpinBox(self.tab)
        self.DRest8Temp.setGeometry(QtCore.QRect(330, 360, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest8Temp.setFont(font)
        self.DRest8Temp.setStyleSheet("QSpinBox { border: 1px inset grey; } \n"
"QSpinBox::up-button { subcontrol-position: left; width: 40px; height: 35px;}\n"
"QSpinBox::down-button { subcontrol-position: right; width: 40px; height: 35px;}")
        self.DRest8Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.DRest8Temp.setSpecialValueText("")
        self.DRest8Temp.setMaximum(200)
        self.DRest8Temp.setProperty("value", 168)
        self.DRest8Temp.setObjectName("DRest8Temp")
        self.DRest1Name = QtWidgets.QLineEdit(self.tab)
        self.DRest1Name.setGeometry(QtCore.QRect(92, 80, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest1Name.setFont(font)
        self.DRest1Name.setObjectName("DRest1Name")
        self.DRest2Name = QtWidgets.QLineEdit(self.tab)
        self.DRest2Name.setGeometry(QtCore.QRect(90, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest2Name.setFont(font)
        self.DRest2Name.setObjectName("DRest2Name")
        self.DRest3Name = QtWidgets.QLineEdit(self.tab)
        self.DRest3Name.setGeometry(QtCore.QRect(90, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest3Name.setFont(font)
        self.DRest3Name.setObjectName("DRest3Name")
        self.DRest4Name = QtWidgets.QLineEdit(self.tab)
        self.DRest4Name.setGeometry(QtCore.QRect(90, 200, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest4Name.setFont(font)
        self.DRest4Name.setObjectName("DRest4Name")
        self.DRest5Name = QtWidgets.QLineEdit(self.tab)
        self.DRest5Name.setGeometry(QtCore.QRect(90, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest5Name.setFont(font)
        self.DRest5Name.setObjectName("DRest5Name")
        self.DRest6Name = QtWidgets.QLineEdit(self.tab)
        self.DRest6Name.setGeometry(QtCore.QRect(90, 280, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest6Name.setFont(font)
        self.DRest6Name.setObjectName("DRest6Name")
        self.DRest7Name = QtWidgets.QLineEdit(self.tab)
        self.DRest7Name.setGeometry(QtCore.QRect(90, 320, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest7Name.setFont(font)
        self.DRest7Name.setObjectName("DRest7Name")
        self.DRest8Name = QtWidgets.QLineEdit(self.tab)
        self.DRest8Name.setGeometry(QtCore.QRect(90, 360, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRest8Name.setFont(font)
        self.DRest8Name.setObjectName("DRest8Name")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(100, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.DRest1Check = QtWidgets.QCheckBox(self.tab)
        self.DRest1Check.setGeometry(QtCore.QRect(30, 80, 31, 31))
        self.DRest1Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest1Check.setText("")
        self.DRest1Check.setObjectName("DRest1Check")
        self.DRest2Check = QtWidgets.QCheckBox(self.tab)
        self.DRest2Check.setGeometry(QtCore.QRect(30, 120, 31, 31))
        self.DRest2Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest2Check.setText("")
        self.DRest2Check.setChecked(False)
        self.DRest2Check.setObjectName("DRest2Check")
        self.DRest3Check = QtWidgets.QCheckBox(self.tab)
        self.DRest3Check.setGeometry(QtCore.QRect(30, 160, 31, 31))
        self.DRest3Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest3Check.setText("")
        self.DRest3Check.setObjectName("DRest3Check")
        self.DRest4Check = QtWidgets.QCheckBox(self.tab)
        self.DRest4Check.setGeometry(QtCore.QRect(30, 200, 31, 31))
        self.DRest4Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest4Check.setText("")
        self.DRest4Check.setChecked(True)
        self.DRest4Check.setObjectName("DRest4Check")
        self.DRest5Check = QtWidgets.QCheckBox(self.tab)
        self.DRest5Check.setGeometry(QtCore.QRect(30, 240, 31, 31))
        self.DRest5Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest5Check.setText("")
        self.DRest5Check.setChecked(False)
        self.DRest5Check.setObjectName("DRest5Check")
        self.DRest6Check = QtWidgets.QCheckBox(self.tab)
        self.DRest6Check.setGeometry(QtCore.QRect(30, 280, 31, 31))
        self.DRest6Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest6Check.setText("")
        self.DRest6Check.setObjectName("DRest6Check")
        self.DRest7Check = QtWidgets.QCheckBox(self.tab)
        self.DRest7Check.setGeometry(QtCore.QRect(30, 320, 31, 31))
        self.DRest7Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest7Check.setText("")
        self.DRest7Check.setChecked(True)
        self.DRest7Check.setObjectName("DRest7Check")
        self.DRest8Check = QtWidgets.QCheckBox(self.tab)
        self.DRest8Check.setGeometry(QtCore.QRect(30, 360, 31, 31))
        self.DRest8Check.setStyleSheet("QCheckBox::indicator {\n"
"     width: 30px;\n"
"     height: 30px;\n"
" }")
        self.DRest8Check.setText("")
        self.DRest8Check.setChecked(True)
        self.DRest8Check.setObjectName("DRest8Check")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.GenerateRecipeButton = QtWidgets.QPushButton(self.tab)
        self.GenerateRecipeButton.setGeometry(QtCore.QRect(670, 300, 93, 81))
        self.GenerateRecipeButton.setObjectName("GenerateRecipeButton")
        self.Tabs.addTab(self.tab, "")
        AutoBrew.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AutoBrew)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        AutoBrew.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AutoBrew)
        self.statusbar.setObjectName("statusbar")
        AutoBrew.setStatusBar(self.statusbar)

        self.retranslateUi(AutoBrew)
        self.Tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AutoBrew)

    def retranslateUi(self, AutoBrew):
        _translate = QtCore.QCoreApplication.translate
        AutoBrew.setWindowTitle(_translate("AutoBrew", "MainWindow"))
        self.PageHeading.setText(_translate("AutoBrew", "Fred\'s AutoBrew Brewing System Start"))
        self.TestPCButton.setText(_translate("AutoBrew", "Test PC"))
        self.TestVerbiage.setText(_translate("AutoBrew", "Float switches, temperature sensors deactivated"))
        self.LivePiButton.setText(_translate("AutoBrew", "Live Pi"))
        self.TestPiButton.setText(_translate("AutoBrew", "Test Pi"))
        self.LivePCButton.setText(_translate("AutoBrew", "Live PC"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.TestorProd), _translate("AutoBrew", "Test"))
        self.label_9.setText(_translate("AutoBrew", "Temp"))
        self.ExitButtonRecipe.setText(_translate("AutoBrew", "Exit"))
        self.label_10.setText(_translate("AutoBrew", "Time"))
        self.BrewButton.setText(_translate("AutoBrew", "Schedule"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.RecipeTab), _translate("AutoBrew", "Recipe"))
        self.label_34.setText(_translate("AutoBrew", "Step"))
        self.label_35.setText(_translate("AutoBrew", "Brew Time"))
        self.label_36.setText(_translate("AutoBrew", "Temp"))
        self.label_37.setText(_translate("AutoBrew", "Temp"))
        self.label_39.setText(_translate("AutoBrew", "+----- Start at -----+"))
        self.label_40.setText(_translate("AutoBrew", "Clock Time"))
        self.label_38.setText(_translate("AutoBrew", "Mash"))
        self.label_41.setText(_translate("AutoBrew", "HLT"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ScheduleTab), _translate("AutoBrew", "Schedule"))
        self.label_15.setText(_translate("AutoBrew", "Elapsed Time:"))
        self.label_16.setText(_translate("AutoBrew", "Time of Day:"))
        self.label_17.setText(_translate("AutoBrew", "Current:"))
        self.label_18.setText(_translate("AutoBrew", "Mash Step"))
        self.label_19.setText(_translate("AutoBrew", "Began"))
        self.label_20.setText(_translate("AutoBrew", "Elapsed"))
        self.label_21.setText(_translate("AutoBrew", "Time to"))
        self.label_22.setText(_translate("AutoBrew", "Next Step"))
        self.label_25.setText(_translate("AutoBrew", "HLT"))
        self.label_26.setText(_translate("AutoBrew", "Upcoming:"))
        self.label_27.setText(_translate("AutoBrew", "HLT"))
        self.label_28.setText(_translate("AutoBrew", "Recipe Step"))
        self.label_30.setText(_translate("AutoBrew", "Begins at"))
        self.StartButton.setText(_translate("AutoBrew", "Start"))
        self.ExitButtonAutoBrew.setText(_translate("AutoBrew", "Exit"))
        self.CurrentMashTempLabel_2.setText(_translate("AutoBrew", "Mash"))
        self.CurrentMashTempLabel_3.setText(_translate("AutoBrew", "Current Temps"))
        self.label_32.setText(_translate("AutoBrew", "Pump"))
        self.label_23.setText(_translate("AutoBrew", "Temp"))
        self.label_24.setText(_translate("AutoBrew", "Temp"))
        self.CurrentMashTempLabel_4.setText(_translate("AutoBrew", "HLT"))
        self.label_33.setText(_translate("AutoBrew", "Burner"))
        self.CurrentMashTempLabel_5.setText(_translate("AutoBrew", "Equip Status"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.AutoBrewTab), _translate("AutoBrew", "AutoBrew"))
        self.PumpRunningLabel.setText(_translate("AutoBrew", "Pump:"))
        self.CurrentMashTempLabel.setText(_translate("AutoBrew", "Current Temp"))
        self.RespectMashFloatSwitchPump.setText(_translate("AutoBrew", "Stop when mash tun is full"))
        self.CurrentHLTTempLabel.setText(_translate("AutoBrew", "Current Temp"))
        self.PumpOn.setText(_translate("AutoBrew", "On"))
        self.RespectHLTTempSet.setText(_translate("AutoBrew", "Stop at set temperature"))
        self.HLTOn.setText(_translate("AutoBrew", "On"))
        self.MashFloatText.setPlaceholderText(_translate("AutoBrew", "Down"))
        self.RespectHLTFloatSwitchHLT.setText(_translate("AutoBrew", "Stop when HLT is empty"))
        self.MashFloatLabel.setText(_translate("AutoBrew", "Mash F/S:"))
        self.HLTRunningLabel.setText(_translate("AutoBrew", "HLT:"))
        self.MashTempSetLabel.setText(_translate("AutoBrew", "Mash Temp"))
        self.HLTTempSetLabel.setText(_translate("AutoBrew", "HLT Temp"))
        self.PumpLabel.setText(_translate("AutoBrew", "Pump"))
        self.RespectHLTFloatSwitchPump.setText(_translate("AutoBrew", "Stop when HLT is empty"))
        self.CurrentMashTempDisplay.setText(_translate("AutoBrew", "0"))
        self.RespectMashTempSet.setText(_translate("AutoBrew", "Stop at set temperature"))
        self.HLTRunningText.setPlaceholderText(_translate("AutoBrew", "Stopped"))
        self.Go.setText(_translate("AutoBrew", "Go"))
        self.HLTFloatLabel.setText(_translate("AutoBrew", "HLT F/S:"))
        self.PumpRunningText.setPlaceholderText(_translate("AutoBrew", "Stopped"))
        self.HLTLabel.setText(_translate("AutoBrew", "HLT"))
        self.HLTOff.setText(_translate("AutoBrew", "Off"))
        self.PumpOff.setText(_translate("AutoBrew", "Off"))
        self.CurrentHLTTempDisplay.setText(_translate("AutoBrew", "0"))
        self.HLTFloatText.setPlaceholderText(_translate("AutoBrew", "Up"))
        self.ReturntoSessionButton.setText(_translate("AutoBrew", "Exit"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ManualControlTab), _translate("AutoBrew", "Manual Control"))
        self.ExportLogButton.setText(_translate("AutoBrew", "Export to .csv"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Log_Tab), _translate("AutoBrew", "Log"))
        self.ExportChartButton.setText(_translate("AutoBrew", "Export to .csv"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ChartTab), _translate("AutoBrew", "Chart"))
        self.label_11.setText(_translate("AutoBrew", "Mash Tun / HLT Differential (Degrees)"))
        self.label_12.setText(_translate("AutoBrew", "Mash Tun Temperature Drop on Mash In"))
        self.label_13.setText(_translate("AutoBrew", "HLT Raise Time (Degrees per Minute)"))
        self.label_42.setText(_translate("AutoBrew", "Mash Tun Raise Time (Degrees per Minute)"))
        self.TwilioLabel1.setText(_translate("AutoBrew", "Twilio SID:"))
        self.TwilioLabel2.setText(_translate("AutoBrew", "Auth Token:"))
        self.TwilioLabel3.setText(_translate("AutoBrew", "Twilio Phone:"))
        self.TwilioLabel4.setText(_translate("AutoBrew", "Send to #:"))
        self.TwilioSID.setText(_translate("AutoBrew", "ACe6ba2ebf969770296498f6ae5a12b3ce"))
        self.TwilioAuthToken.setText(_translate("AutoBrew", "c67b52a7631ac3d7fd5ae98dc1ca2339"))
        self.TwilioPhone.setText(_translate("AutoBrew", "+19412020403"))
        self.TwilioSendTo.setText(_translate("AutoBrew", "+19415499312"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.SettingsTab), _translate("AutoBrew", "Settings"))
        self.label_14.setText(_translate("AutoBrew", "Time"))
        self.label_29.setText(_translate("AutoBrew", "Temp"))
        self.DRest1Name.setText(_translate("AutoBrew", "Acid Rest"))
        self.DRest2Name.setText(_translate("AutoBrew", "Peptidase Rest"))
        self.DRest3Name.setText(_translate("AutoBrew", "Proteinase Rest"))
        self.DRest4Name.setText(_translate("AutoBrew", "Beta Rest"))
        self.DRest5Name.setText(_translate("AutoBrew", "Dry Moderate"))
        self.DRest6Name.setText(_translate("AutoBrew", "Body Moderate"))
        self.DRest7Name.setText(_translate("AutoBrew", "Alpha Rest"))
        self.DRest8Name.setText(_translate("AutoBrew", "Mash Out"))
        self.label_31.setText(_translate("AutoBrew", "Name"))
        self.label_43.setText(_translate("AutoBrew", "Default?"))
        self.GenerateRecipeButton.setText(_translate("AutoBrew", "Generate\n"
"Recipe"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("AutoBrew", "Rests"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AutoBrew = QtWidgets.QMainWindow()
    ui = Ui_AutoBrew()
    ui.setupUi(AutoBrew)
    AutoBrew.show()
    sys.exit(app.exec_())

